### ISSUE TITLE
Does this take the "incoming" tag?

### ISSUE THREAD

**Issue by RobinKnipe** [UKHomeOffice/lev-api-spec#17]
https://github.com/UKHomeOffice/lev-api-spec/blob/2a819c195e7287c89bc27f3e5b6fe5da25e2f53b/.drone.yml#L29

i.e. will this take the tag event that triggered this build and use that [git] tag to create the tag for the docker image @daniel-ac-martin ?

**Comment by daniel-ac-martin** [comment]
Yes. - http://plugins.drone.io/drone-plugins/drone-docker/#autotag
