### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by KSW2-21** [UKHomeOffice/lev-api-spec#37]
Hello. I'm looking to use this service but need more information about it? How can I integrate this and is there a cost of doing so?

Also, what is the main point of contact for queries related to LifeEvents?

Thanks

**Comment by RobinKnipe** [comment]
Hi @KSW2-21 
The API that this [spec] describes, is currently used exclusively by organisations within the UK Government. There are some private sector trials already planned, but still a way off. If you represent a UK business, and are able to comply with the associated GDPR and Data Protection regulations, and would like to present a case for access to the Life Event Verification API, you can contact: lev-service@digital.homeoffice.gov.uk
Thanks,
Robin.
